// backend/src/routes/subscriptions.js
const express = require('express');
const pool = require('../config/db');
const { verifyToken } = require('../middlewares/auth');

const router = express.Router();

// Get all subscription plans
router.get('/plans', async (req, res) => {
  try {
    const [plans] = await pool.query(
      'SELECT * FROM subscription_plans ORDER BY price ASC'
    );

    return res.json({
      success: true,
      plans
    });
  } catch (error) {
    console.error('Error fetching subscription plans:', error);
    return res.status(500).json({ 
      success: false,
      message: 'Lỗi khi tải gói subscription' 
    });
  }
});

// Get user's current subscription
router.get('/current', verifyToken, async (req, res) => {
  try {
    const userId = req.user.id;
    
    const [subscriptions] = await pool.query(
      `SELECT us.*, 
              sp.name as plan_name, 
              sp.description,
              sp.audio_quality,
              sp.ad_free,
              sp.currency,
              sp.trial_period_days
       FROM user_subscriptions us
       JOIN subscription_plans sp ON us.subscription_plan_id = sp.id
       WHERE us.user_id = ? AND us.status = 'active' AND us.end_date > NOW()
       ORDER BY us.end_date DESC
       LIMIT 1`,
      [userId]
    );

    if (subscriptions.length === 0) {
      return res.json({
        success: true,
        subscription: null,
        is_premium: false
      });
    }

    return res.json({
      success: true,
      subscription: subscriptions[0],
      is_premium: true
    });
  } catch (error) {
    console.error('Error fetching current subscription:', error);
    return res.status(500).json({ 
      success: false,
      message: 'Lỗi khi tải thông tin subscription' 
    });
  }
});

// Create subscription (after payment)
router.post('/create', verifyToken, async (req, res) => {
  try {
    const userId = req.user.id;
    const { 
      plan_id, 
      payment_gateway, 
      payment_method_token, 
      auto_renew = false,
      prorated_amount 
    } = req.body;

    if (!plan_id) {
      return res.status(400).json({
        success: false,
        message: 'Thiếu plan_id'
      });
    }

    // Get plan details
    const [plans] = await pool.query(
      'SELECT * FROM subscription_plans WHERE id = ?',
      [plan_id]
    );

    if (plans.length === 0) {
      return res.status(404).json({
        success: false,
        message: 'Không tìm thấy gói subscription'
      });
    }

    const plan = plans[0];

    // Create subscription (end_date is auto-generated by database)
    const [result] = await pool.query(
      `INSERT INTO user_subscriptions 
       (user_id, subscription_plan_id, duration_days, status, 
        payment_status, payment_method_token, payment_gateway, 
        auto_renew, prorated_amount)
       VALUES (?, ?, ?, 'active', 'completed', ?, ?, ?, ?)`,
      [
        userId, 
        plan_id, 
        plan.duration_days, 
        payment_method_token || null, 
        payment_gateway || 'demo', 
        auto_renew,
        prorated_amount || plan.price
      ]
    );

    // Get the created subscription with calculated end_date
    const [newSubscription] = await pool.query(
      `SELECT * FROM user_subscriptions WHERE id = ?`,
      [result.insertId]
    );

    return res.status(201).json({
      success: true,
      message: 'Đăng ký Premium thành công!',
      subscription_id: result.insertId,
      subscription: newSubscription[0]
    });
  } catch (error) {
    console.error('Error creating subscription:', error);
    
    // Check for duplicate subscription error
    if (error.code === 'ER_DUP_ENTRY') {
      return res.status(400).json({ 
        success: false,
        message: 'Bạn đã có subscription active cho gói này rồi' 
      });
    }
    
    return res.status(500).json({ 
      success: false,
      message: 'Lỗi khi tạo subscription' 
    });
  }
});

// Cancel subscription
router.post('/cancel', verifyToken, async (req, res) => {
  try {
    const userId = req.user.id;

    await pool.query(
      `UPDATE user_subscriptions 
       SET status = 'canceled', auto_renew = FALSE 
       WHERE user_id = ? AND status = 'active'`,
      [userId]
    );

    return res.json({
      success: true,
      message: 'Đã hủy subscription'
    });
  } catch (error) {
    console.error('Error cancelling subscription:', error);
    return res.status(500).json({ 
      success: false,
      message: 'Lỗi khi hủy subscription' 
    });
  }
});

// Check if user is premium
router.get('/check-premium', verifyToken, async (req, res) => {
  try {
    const userId = req.user.id;
    
    const [subscriptions] = await pool.query(
      `SELECT id FROM user_subscriptions 
       WHERE user_id = ? AND status = 'active' AND end_date > NOW()
       LIMIT 1`,
      [userId]
    );

    return res.json({
      success: true,
      is_premium: subscriptions.length > 0
    });
  } catch (error) {
    console.error('Error checking premium status:', error);
    return res.status(500).json({ 
      success: false,
      message: 'Lỗi khi kiểm tra trạng thái premium' 
    });
  }
});

module.exports = router;
